"""empty message

Revision ID: 14cc2a0c9a3
Revises: 46b3683d4b1a
Create Date: 2016-10-20 11:00:55.864891

"""

# revision identifiers, used by Alembic.
revision = '14cc2a0c9a3'
down_revision = '46b3683d4b1a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gender', sa.String(length=64), nullable=True))
    op.drop_column('users', 'location')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('location', sa.VARCHAR(length=64), nullable=True))
    op.drop_column('users', 'gender')
    ### end Alembic commands ###
