"""empty message

Revision ID: 2264ac6d29ec
Revises: 53e7593e474b
Create Date: 2016-10-19 18:03:08.565634

"""

# revision identifiers, used by Alembic.
revision = '2264ac6d29ec'
down_revision = '53e7593e474b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password_hash', sa.String(length=128), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password_hash')
    ### end Alembic commands ###
