"""empty message

Revision ID: 310a6641e3a2
Revises: 2264ac6d29ec
Create Date: 2016-10-19 19:42:50.478162

"""

# revision identifiers, used by Alembic.
revision = '310a6641e3a2'
down_revision = '2264ac6d29ec'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('title', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'title')
    ### end Alembic commands ###
