"""empty message

Revision ID: 7de09351665
Revises: 360fab9fad0
Create Date: 2016-10-19 00:30:51.098246

"""

# revision identifiers, used by Alembic.
revision = '7de09351665'
down_revision = '360fab9fad0'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
